### ISSUE TITLE
Add a donors page

### ISSUE THREAD

**Issue by shinjanxp** [covid-19-ppe-tracker/covid-19-ppe-tracker#7]
Some users want to donate funds to acquire and distribute PPE
Create a new page that takes donor contact info and saves in DB
Form should contain:
- Name
- Contact
- Location
- Email
- Amount willing to donate

Create a new model and migration to store this info

**Comment by oyeb** [comment]
Probably suggest running a fund raising campaign or just publicise a UPI ID.
We can list out donors in a hall-of-fame page.
